[package]
name = "joyshop"
version = "0.1.0"
authors = ["Sofia Winters <a@sofia.win>"]
edition = "2018"

[dependencies]
joycon-rs = "0.6.1"
win_key_codes = "0.1.2"
winapi = { version = "0.3.9", features = ["winuser"] }
